CUR_DIR		:= lib/compiler-rt/lib/powerpc/

OBJS := divtc3.o fixtfdi.o fixunstfdi.o floatditf.o floatunditf.o gcc_qadd.o \
	gcc_qdiv.o gcc_qmul.o gcc_qsub.o multc3.o

# Not compiled: restFP.S saveFP.S

LIBSUBDIRS	:=

include $Omk/libsubdirs.mk
