CUR_DIR		:= lib/libc/wchar/

OBJS := wcscat.o wcscpy.o wcslcpy.o wcsncmp.o wcsrchr.o wcswidth.o wmemcpy.o \
	wcpcpy.o wcschr.o wcscspn.o wcslen.o wcsncpy.o wcsspn.o wcsxfrm.o \
	wmemmove.o wcpncpy.o wcscmp.o wcsdup.o wcsncasecmp.o wcsnlen.o wcsstr.o \
	wmemchr.o wmemset.o wcscasecmp.o wcscoll.o wcslcat.o wcsncat.o wcspbrk.o \
	wcstok.o wmemcmp.o

LIBSUBDIRS	:=

include $Omk/libsubdirs.mk
