CUR_DIR		:= lib/libc/stdio/

OBJS := asprintf.o fgetpos.o fprintf.o ftell.o putw.o snprintf.o \
	wsetup.o clrerr.o fgets.o fpurge.o funopen.o refill.o sprintf.o \
	vfscanf.o fclose.o fputc.o fvwrite.o sscanf.o \
	vprintf.o fileno.o fputs.o rewind.o stdio.o vscanf.o \
	feof.o findfp.o fread.o fwalk.o mktemp.o rget.o tempnam.o vsnprintf.o \
	ferror.o flags.o freopen.o fwrite.o printf.o scanf.o tmpfile.o \
	vsprintf.o fflush.o fscanf.o getc.o putc.o setbuf.o tmpnam.o vsscanf.o \
	fgetc.o fseek.o getchar.o putchar.o setbuffer.o ungetc.o \
	wbuf.o fgetln.o fopen.o fsetpos.o gets.o puts.o setvbuf.o vasprintf.o \
	makebuf.o remove.o vfprintf.o flockfile.o

# Not compiled: fdopen.c

LIBSUBDIRS	:=

include $Omk/libsubdirs.mk
