CUR_DIR		:= lib/compiler-rt/lib/

OBJS := absvdi2.o absvsi2.o absvti2.o adddf3.o addsf3.o addvdi3.o addvsi3.o \
	addvti3.o ashldi3.o ashlti3.o ashrdi3.o ashrti3.o clear_cache.o clzdi2.o \
	clzsi2.o clzti2.o cmpdi2.o cmpti2.o comparedf2.o comparesf2.o ctzdi2.o ctzsi2.o \
	ctzti2.o divdc3.o divdf3.o divdi3.o divmoddi4.o divmodsi4.o divsc3.o divsf3.o \
	divsi3.o divti3.o divxc3.o enable_execute_stack.o eprintf.o extendsfdf2.o \
	ffsdi2.o ffsti2.o fixdfdi.o fixdfsi.o fixdfti.o fixsfdi.o fixsfsi.o fixsfti.o \
	fixunsdfdi.o fixunsdfsi.o fixunsdfti.o fixunssfdi.o fixunssfsi.o fixunssfti.o \
	fixunsxfdi.o fixunsxfsi.o fixunsxfti.o fixxfdi.o fixxfti.o floatdidf.o \
	floatdisf.o floatdixf.o floatsidf.o floatsisf.o floattidf.o floattisf.o \
	floattixf.o floatundidf.o floatundisf.o floatundixf.o floatunsidf.o \
	floatunsisf.o floatuntidf.o floatuntisf.o floatuntixf.o gcc_personality_v0.o \
	int_util.o lshrdi3.o lshrti3.o moddi3.o modsi3.o modti3.o muldc3.o muldf3.o \
	muldi3.o mulodi4.o mulosi4.o muloti4.o mulsc3.o mulsf3.o multi3.o mulvdi3.o \
	mulvsi3.o mulvti3.o mulxc3.o negdf2.o negdi2.o negsf2.o negti2.o negvdi2.o \
	negvsi2.o negvti2.o paritydi2.o paritysi2.o parityti2.o popcountdi2.o \
	popcountsi2.o popcountti2.o powidf2.o powisf2.o powitf2.o powixf2.o subdf3.o \
	subsf3.o subvdi3.o subvsi3.o subvti3.o trampoline_setup.o truncdfsf2.o ucmpdi2.o \
	ucmpti2.o udivdi3.o udivmoddi4.o udivmodsi4.o udivmodti4.o udivsi3.o udivti3.o \
	umoddi3.o umodsi3.o umodti3.o unwind_cpp.o

LIBSUBDIRS	:= $(STOS_ARCH)/

include $Omk/libsubdirs.mk
