/* auto-generated by gensyscalls.py, do not touch */
#ifndef _BIONIC_STOS_UNISTD_H_

#ifdef __cplusplus
extern "C" {
#endif

int              __open (const char*, int, mode_t);
ssize_t          read (int, void*, size_t);
ssize_t          write (int, const void*, size_t);
int              close (int);
int              mount (const char*, const char*, const char*);
off_t            lseek (int, off_t, int);
int              execve (const char*, char* const*, char* const*);
pid_t            clone (int);
void*            mmap (void*, size_t, int, int, int, off_t);
int              munmap (void*, size_t);
int              mprotect (void*, size_t, int);
void             _exit (int);
int              fstat (int, struct stat*);
pid_t            waitpid (pid_t pid, int* status, int options);
pid_t            getpid (void);
uid_t            getuid (void);
gid_t            getgid (void);
int              __fcntl (int, int, void*);
int              chdir (const char*);
pid_t            getppid (void);
int              __getcwd (char*, size_t);
int              unlink (const char*);
int              stat (const char*, struct stat*);
#ifdef __cplusplus
}
#endif

#endif /* _BIONIC_STOS_UNISTD_H_ */
