CUR_DIR		:= lib/compiler-rt/lib/i386/

OBJS := ashldi3.o ashrdi3.o divdi3.o floatdidf.o floatdisf.o \
	floatdixf.o floatundidf.o floatundisf.o floatundixf.o \
	lshrdi3.o moddi3.o muldi3.o udivdi3.o umoddi3.o

LIBSUBDIRS	:=

include $Omk/libsubdirs.mk
