CUR_DIR		:= lib/compiler-rt/lib/arm/

OBJS := adddf3vfp.o addsf3vfp.o aeabi_idivmod.o aeabi_ldivmod.o aeabi_memcmp.o \
	aeabi_memcpy.o aeabi_memmove.o aeabi_memset.o aeabi_uidivmod.o aeabi_uldivmod.o \
	bswapdi2.o bswapsi2.o comparesf2.o divdf3vfp.o divmodsi4.o divsf3vfp.o divsi3.o \
	eqdf2vfp.o eqsf2vfp.o extendsfdf2vfp.o fixdfsivfp.o fixsfsivfp.o fixunsdfsivfp.o \
	fixunssfsivfp.o floatsidfvfp.o floatsisfvfp.o floatunssidfvfp.o \
	floatunssisfvfp.o gedf2vfp.o gesf2vfp.o gtdf2vfp.o gtsf2vfp.o ledf2vfp.o \
	lesf2vfp.o ltdf2vfp.o ltsf2vfp.o modsi3.o muldf3vfp.o mulsf3vfp.o nedf2vfp.o \
	negdf2vfp.o negsf2vfp.o nesf2vfp.o restore_vfp_d8_d15_regs.o \
	save_vfp_d8_d15_regs.o subdf3vfp.o subsf3vfp.o switch16.o \
	switch32.o switch8.o switchu8.o sync_synchronize.o truncdfsf2vfp.o udivmodsi4.o \
	udivsi3.o umodsi3.o unorddf2vfp.o unordsf2vfp.o

LIBSUBDIRS	:=

include $Omk/libsubdirs.mk
