CUR_DIR		:= lib/libc/stdlib/

OBJS := assert.o atexit.o atoi.o atol.o atoll.o bsearch.o ctype_.o div.o exit.o \
	getenv.o ldiv.o lldiv.o locale.o \
	putenv.o qsort.o setenv.o setjmperr.o strntoimax.o \
	strntoumax.o strtoimax.o strtol.o strtoll.o strtoul.o strtoull.o \
	strtoumax.o tolower_.o toupper_.o wchar.o jrand48.o lrand48.o mrand48.o \
	nrand48.o _rand48.o seed48.o srand48.o


# not compiled: strtod.c

LIBSUBDIRS	:=

include $Omk/libsubdirs.mk
