CUR_DIR		:= lib/libc/string/

OBJS := bcopy.o memcpy.o memswap.o strcmp.o strerror.o strncat.o \
	strpbrk.o strtok.o index.o memmem.o strcasecmp.o strcoll.o strerror_r.o \
	strncmp.o strrchr.o memccpy.o memmove.o strcasestr.o strcpy.o strlcat.o \
	strncpy.o strsep.o strxfrm.o memchr.o memrchr.o strcat.o strcspn.o \
	strlcpy.o strndup.o strspn.o memcmp.o memset.o strchr.o strdup.o \
	strlen.o strnlen.o strstr.o strtotimeval.o

LIBSUBDIRS	:=

include $Omk/libsubdirs.mk
